### PR TITLE
Add command to pull all docker images

### PR DESCRIPTION
**Pull request by malikoth**
OH SURE!  Now that this all got beautifully merged into Prezto, NOW I come up with this command!

This new command, `dkIPL` will issue a `docker pull` command for each repository in your list of docker images.  Some of them report `Image is up to date`.  Some of them report `Error response from daemon: repository not found: does not exist or no pull access`.  I think that's fine, if you've got an image whose tag doesn't actually point to an image in the registry.

What do you think?  Should I submit a PR to Prezto with it?  As far as I'm concerned, this repo is still the authoritative source of docker aliases...

This command inspired from here:  http://www.googlinux.com/update-all-docker-images/

### CODE REVIEW

**Comment by akarzim** [comment]
Thanks Kyle! It seems to be a useful alias.

May I suggest `docker images --format '{{ .Repository }}' | grep -v '^<none>$' | xargs -L1 docker pull` to avoid to pull images without repository name?

On the alias itself, as `dkI` stands for `docker image` and not `docker images`, I propose `dkplI` as it is kind of a `docker pull` and it is very similar to `dkrmI`. What do you think?

Concerning Prezto, I don't know exactly how to deal with it since I've switched to Zplug…
There is no hard link between this two repositories and backport from one to the other will be a manual work anyway. To submit a PR to Prezto too may be a good idea. I'll do my best to keep this repo as close as possible as the Prezto one's.

**Comment by malikoth** [comment]
I like `dkplI` better, it's easier to type.

But on the other hand, `docker images` is just an alias for `docker image ls`, which if I just expanded that out, then this would officially belong with the rest of the `docker image` block.

**Comment by malikoth** [comment]
> But on the other hand, docker images is just an alias for docker image ls, which if I just expanded that out, then this would officially belong with the rest of the docker image block.

But on the other _other_ hand, `docker image ls` is just one part of the command, which is multiple distinct commands glued together with pipes.  This one isn't just a shortcut to a longer-named docker command, it's its own specially crafted command.  Therefore, I think it should stay `dkplI` and you should merge it if you like it.

**Comment by akarzim** [comment]
Thanks Kyle, feel free to propose this little PR on the Prezto repo too.

**Pull request merged**
